name: PluginDocumentation
version: 1.0.0
description: A plugin aimed at centralizing plugin documentation in game.
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.PluginDocumentation.Main.PluginDocumentation
commands:
   contributors:
      description: Prints a list of contributors to the project.
      usage: /<command>
      permission: PluginDocumentation.contributors
      permission-message: You don't have permission
      aliases: [authors,contributers]
   dump:
      description: Dumps all (if present) cached data.
      usage: /<command>
      permission: PluginDocumentation.dump
      permission-message: You don't have permission
   plugin-list:
      description: Lists all the currently supported plugins.
      usage: /<command>
      permission: PluginDocumentation.plugin-list
      permission-message: You don't have permission
      aliases: [plugins-list,pluginlist,pluginslist]
   plugin-help:
      description: Attempts to fetch documentation for the given plugin.
      usage: /<command> <plugin>
      permission: PluginDocumentation.plugin-help
      permission-message: You don't have permission
      aliases: [plugins-help,pluginhelp,pluginshelp]
   book-converter:
      description: Attempts to pastebin the contents of the book you’re holding.
      usage: /<command>
      permission: PluginDocumentation.book-converter
      permission-message: You don't have permission
      aliases: [bookconverter]

permissions:
   PluginDocumentation.*:
      description: Gives access to all PluginDocumentation commands
   PluginDocumentation.contributors:
      description: Prints a list of contributors to the project.
      default: true
   PluginDocumentation.dump:
      description: Dumps all (if present) cached data.
   PluginDocumentation.plugin-list:
      description: Lists all the currently supported plugins.
      default: true
   PluginDocumentation.plugin-help:
      description: Attempts to fetch documentation for the given plugin.
      default: true
   PluginDocumentation.book-converter:
      description: Attempts to pastebin the contents of the book you’re holding.