name: PluginDocumentation
version: 1.0.0
description: A plugin aimed at centralizing plugin documentation in game.
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.PluginDocumentation.Main.PluginDocumentation
commands:
   contributors:
      description: Prints a list of contributors to the project.
      usage: /<command>
      permission: PluginDocumentation.contributors
      permission-message: You don't have permission
      aliases: [authors,contributers]
   dump:
      description: Dumps all (if present) cached data.
      usage: /<command>
      permission: PluginDocumentation.dump
      permission-message: You don't have permission
   plugin-list:
      description: Lists all the currently supported plugins.
      usage: /<command>
      permission: PluginDocumentation.plugin-list
      permission-message: You don't have permission
      aliases: [plugins-list,pluginlist,pluginslist]

permissions:
   PluginDocumentation.*:
      description: Gives access to all PluginDocumentation commands
   PluginDocumentation.contributors:
      description: Prints a list of contributors to the project.
      default: true
   PluginDocumentation.dump:
      description: Dumps all (if present) cached data.
   PluginDocumentation.plugin-list:
      description: Lists all the currently supported plugins.
      default: true